import datetime
import os
import pprint
import spacy
from spacy.training.example import Example
from spacy.util import minibatch


# Carregar um modelo base em português
nlp = spacy.load("pt_core_news_lg")

# Adicionar o pipeline de classificação de texto
config = {
    "threshold": 0.5,  # Ajuste o threshold conforme necessário
    "model": {
        "@architectures": "spacy.TextCatBOW.v1",
        "exclusive_classes": True,  # Se as classes forem mutuamente exclusivas
        "ngram_size": 3,
        "no_output_layer": False
    }
}
textcat = nlp.add_pipe("textcat", config=config)

# Adicionar rótulos ao textcat
textcat.add_label("LABEL_TAG_BUSCAR_INFORMACOES")
textcat.add_label("LABEL_TAG_REALIZAR_TRANSACOES")
textcat.add_label("LABEL_TAG_ASSISTENCIA_TECNICA")
textcat.add_label("LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS")
textcat.add_label("LABEL_TAG_SUPORTE_AO_CLIENTE")
textcat.add_label("LABEL_TAG_QUESTOES_ADMINISTRATIVAS")
textcat.add_label("LABEL_TAG_INTERACAO_SOCIAL")
textcat.add_label("LABEL_TAG_EDUCACAO_E_TREINAMENTO")

# Dados de treinamento (exemplo simples)
train_data = [
  
    # LABEL_TAG_BUSCAR_INFORMACOES
    ("Solicitar informações sobre produtos ou serviços", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 1, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    ("Pedir detalhes sobre horários de funcionamento, localização ou contato", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 1, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    ("Buscar informações sobre políticas da empresa (trocas, devoluções, garantias)", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 1, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    
    # LABEL_TAG_REALIZAR_TRANSACOES
    ("Fazer compras ou reservas", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 1, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    ("Solicitar cotações ou orçamentos", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 1, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    ("Pagar contas ou fazer transferências", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 1, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    ("gerar ou pegar o Boleto do mês ou pagamentos pendentes", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 1, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    
    # LABEL_TAG_ASSISTENCIA_TECNICA
    ("Reportar problemas técnicos", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 1, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    ("Solicitar suporte para configurar ou usar produtos", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 1, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    ("Pedir ajuda para resolver erros ou bugs", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 1, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    
    # LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS
    ("Verificar o status de um pedido ou entrega", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 1, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    ("Solicitar atualizações sobre envios ou rastreamento", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 1, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    
    # LABEL_TAG_SUPORTE_AO_CLIENTE
    ("Registrar reclamações ou feedbacks", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 1, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    ("Pedir ajuda para resolver problemas com produtos ou serviços", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 1, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    ("Solicitar informações sobre programas de fidelidade ou recompensas", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 1, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    
    # LABEL_TAG_QUESTOES_ADMINISTRATIVAS
    ("Atualizar informações pessoais ou de conta", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 1, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    ("Recuperar senhas ou nomes de usuário", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 1, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    ("Solicitar cancelamentos de contas ou serviços", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 1, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    
    # LABEL_TAG_INTERACAO_SOCIAL
    ("Fazer perguntas triviais ou pessoais (p. ex., piadas, curiosidades)", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 1, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    ("Buscar recomendações ou sugestões", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 1, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    ("Participar de jogos ou quizzes interativos", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 1, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 0}}),
    
    # LABEL_TAG_EDUCACAO_E_TREINAMENTO
    ("Solicitar materiais de estudo ou treinamento", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 1}}),
    ("Fazer perguntas sobre tópicos educacionais", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 1}}),
    ("Buscar ajuda com lições de casa ou projetos", {"cats": {"LABEL_TAG_BUSCAR_INFORMACOES": 0, "LABEL_TAG_REALIZAR_TRANSACOES": 0, "LABEL_TAG_ASSISTENCIA_TECNICA": 0, "LABEL_TAG_ACOMPANHAMENTO_DE_PEDIDOS": 0, "LABEL_TAG_SUPORTE_AO_CLIENTE": 0, "LABEL_TAG_QUESTOES_ADMINISTRATIVAS": 0, "LABEL_TAG_INTERACAO_SOCIAL": 0, "LABEL_TAG_EDUCACAO_E_TREINAMENTO": 1}})
]


# Treinar o modelo
optimizer = nlp.initialize()
EPOCHS = 1000
BATCHS = 5

for i in range(EPOCHS):  # Número de épocas de treinamento
    losses = {}
    batches = minibatch(train_data, size=BATCHS)
    for batch in batches:
        examples = [Example.from_dict(nlp.make_doc(text), annotations) for text, annotations in batch]
        nlp.update(examples, sgd=optimizer, losses=losses)
    print(f"Losses at iteration {i}:", losses)

# Salvar o modelo treinado
date = str(datetime.datetime.now()).replace(":", "-").replace(" ", "T")
full_path_actual = os.path.dirname(os.path.abspath(__file__))
name_model = input("Defina um aliases para o modelo: ")
path_saved_model = os.path.join(full_path_actual, "..", "..", "models", f"textcat_model_{name_model}_{date}")

nlp.to_disk(path_saved_model)

print("\n\n\nMODELO SALVO EM:", path_saved_model, "\n\n")

# Carregar o modelo treinado
nlp = spacy.load(path_saved_model)

# Fazer previsões
doc = nlp("Queria saber como gerar o meu boleto")
doc_cats = doc.cats

# Encontrar a label com a maior probabilidade
max_label = max(doc_cats, key=doc_cats.get)

pprint.pprint(doc_cats) 
# Imprimir a label e sua probabilidade
print(f"A label com a maior probabilidade é '{max_label}' com uma chance de {doc_cats[max_label]:.2f}")